{
 "title": "Monitor Services",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Prometheus Uptime",
   "type": "singlestat",
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{instance=\"localhost:9090\",job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_org_label_schema_group=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_user_seconds_total{container_label_org_label_schema_group=\"monitoring\"}[1m]) * 100  / scalar(count(node_cpu_seconds_total{mode=\"user\"})))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{container_label_org_label_schema_group=\"monitoring\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Prometheus Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{job=\"prometheus\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "process_open_fds{job=\"prometheus\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\"}",
     "legendFormat": "Target heap size"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"prometheus\"}",
     "legendFormat": "Next GC"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"prometheus\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "WAL Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_fsync_duration_seconds_sum[1m]) / rate(prometheus_tsdb_wal_fsync_duration_seconds_count[1m])",
     "legendFormat": "Fsync Latency"
    },
    {
     "expr": "rate(prometheus_tsdb_wal_truncate_duration_seconds_sum[1m]) / rate(prometheus_tsdb_wal_truncate_duration_seconds_count[1m])",
     "legendFormat": "Truncate Latency"
    }
   ]
  },
  {
   "title": "TSDB Reloads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total[10m])",
     "legendFormat": "Reloads"
    }
   ]
  },
  {
   "title": "TSDB Problems",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_wal_corruptions_total[10m])",
     "legendFormat": "WAL Corruptions"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total[10m])",
     "legendFormat": "Reload Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_head_series_not_found[10m])",
     "legendFormat": "Head Series Not Found"
    },
    {
     "expr": "rate(prometheus_tsdb_compactions_failed_total[10m])",
     "legendFormat": "Compaction Failures"
    },
    {
     "expr": "rate(prometheus_tsdb_retention_cutoffs_failures_total[10m])",
     "legendFormat": "Retention Cutoff Failures"
    }
   ]
  },
  {
   "title": "Evaluation time of rule groups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_duration_seconds_sum[1m])",
     "legendFormat": "Rule evaluation duration"
    }
   ]
  }
 ]
}